name: Hugo Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0 

      - name: Setup Node.js Env
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Create site
        run: hugo --minify

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          external_repository: hollacs/hollacs.github.io
          publish_dir: ./public
          keep_files: false
          commit_message: "Deploy updates"

